version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/mnt/Data/open-webui-data:/app/backend/data:z
    environment:
      - OLLAMA_BASE_URLS=http://ollama:11434;http://ollamaAMD:11434;http://ollamaCPU:11434
      - ANONYMIZED_TELEMETRY=False
      - RAG_EMBEDDING_ENGINE=ollama

  ollamaAMD:
    image: docker.io/ollama/ollama:latest
    container_name: ollamaAMD
    restart: unless-stopped
    ports:
      - "127.0.0.1:11435:11434"
    volumes:
      - /var/mnt/Data/ollama-models:/root/.ollama:z
    devices:
      - /dev/dri
    security_opt:
      - label=disable
    environment:
      - OLLAMA_IGPU_ENABLE=1
      - OLLAMA_NO_CLOUD=true
      - OLLAMA_ORIGINS=moz-extension://*,vscode-webview://*,http://localhost:8080,http://127.0.0.1:8080

  ollamaCPU:
    image: docker.io/ollama/ollama:latest
    container_name: ollamaCPU
    restart: unless-stopped
    ports:
      - "127.0.0.1:11436:11434"
    volumes:
      - /var/mnt/Data/ollama-models:/root/.ollama:z
    security_opt:
      - label=disable
    environment:
      - OLLAMA_NO_CLOUD=true
      - OLLAMA_ORIGINS=moz-extension://*,vscode-webview://*,http://localhost:8080,http://127.0.0.1:8080

  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - /var/mnt/Data/ollama-models:/root/.ollama:z
    security_opt:
      - label=disable
    environment:
      - OLLAMA_NO_CLOUD=true
      - OLLAMA_ORIGINS=moz-extension://*,vscode-webview://*,http://localhost:8080,http://127.0.0.1:8080
    devices:
      - nvidia.com/gpu=all
